### ISSUE TITLE
gui界面文字消失和吞物品无法合成

### ISSUE THREAD

**Issue by axlmly** [Yuqi154/mystias_izakaya#10]
![image](https://github.com/Yuqi154/mystias_izakaya/assets/41771421/6e0d7ff2-f2d7-4429-a956-9e9ed5169d35)
从0.0.6g开始就无法合成出食物,到了0.0.7gui汤圆合成的文字都没了

**Comment by axlmly** [comment]
版本1.20.1 一开始还以为是其他mod覆盖了,拿出来单独一个mod测还是一样

**Comment by Yuqi154** [comment]
在0.0.7a已修复
