### ISSUE TITLE
[bug]货币不会消失

### ISSUE THREAD

**Issue by Mysitia** [Yuqi154/mystias_izakaya#13]
-来自MC百科评论区
mod版本：0.0.7e
MC版本：1.19.2

所有货币在使用后都不会消失，可以无限存入银行。
经测试，1.20.1版本则并无此问题。

**Comment by Yuqi154** [comment]
该问题可能由创造模式导致。
在最新的提交里已经测试通过，于创造模式下使用不会消耗，生存模式下正常消耗。
